import React from "react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, ArrowUpRight, Building2, CircleCheck, Cloud, Eye, Gauge, Loader2, Radio, ShieldCheck, Sparkles, type LucideIcon } from "lucide-react";

function time(value: string | Date | null | undefined) { return value ? new Date(value).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "—"; }

type ClientOverview = {
  gateway: { name: string; status: string; operatingMode: string };
  machines: { id: number; machineKey: string; name: string; area: string; state: string; connectionStatus: string; cycleCount: number; runtimeSeconds: number }[];
  alerts: { id: number; severity: string; title: string; description: string; status: string; createdAt: string | Date }[];
  events: { id: number; eventType: string; createdAt: string | Date }[];
};

export default function ClientPortal() {
  const overview = trpc.operations.clientOverview.useQuery(undefined, { refetchInterval: 20_000 });
  if (overview.isLoading) return <div className="grid min-h-[70vh] place-items-center text-slate-400"><Loader2 className="mr-2 inline h-5 w-5 animate-spin" />Cargando espacio de cliente…</div>;
  if (!overview.data) return <div className="grid min-h-[70vh] place-items-center text-slate-400">No se ha podido cargar tu espacio operativo.</div>;
  const data = overview.data as ClientOverview;
  const connected = data.machines.filter(machine => machine.connectionStatus === "connected").length;
  const activeAlerts = data.alerts.filter(alert => alert.status === "active").length;
  return <div className="operations-shell min-h-screen -m-4 p-4 md:-m-6 md:p-6"><div className="mx-auto max-w-[1440px] space-y-5">
    <section className="glass-panel overflow-hidden rounded-3xl p-6 md:p-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-4 flex items-center gap-2"><Badge className="border-violet-200/30 bg-violet-200/10 text-violet-100">CLIENT PORTAL</Badge><span className="font-mono text-[10px] tracking-[.15em] text-slate-400">READ ONLY / SIMULATION</span></div><h1 className="max-w-2xl text-3xl font-semibold tracking-tight text-white md:text-4xl">Claridad operativa, sin exponer los controles de planta.</h1><p className="mt-4 max-w-2xl leading-7 text-slate-300">Consulta el estado, disponibilidad, alertas y trazabilidad de tus activos. Las órdenes y el gateway permanecen en el centro de control autorizado.</p></div><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/25 p-4"><ShieldCheck className="h-7 w-7 text-cyan-200" /><div><p className="text-sm font-medium text-white">Aislamiento por sesión</p><p className="mt-1 text-xs text-slate-400">Tus registros se consultan desde tu espacio autenticado.</p></div></div></div></section>
    <section className="grid gap-4 md:grid-cols-3"><Card className="glass-panel"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.14em] text-slate-400">Disponibilidad</p><p className="mt-3 text-3xl font-semibold text-white">{connected}/{data.machines.length}</p><p className="mt-2 text-xs text-emerald-200">Activos conectados</p></div><CircleCheck className="h-6 w-6 text-emerald-200" /></div></CardContent></Card><Card className="glass-panel"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.14em] text-slate-400">Alertas</p><p className="mt-3 text-3xl font-semibold text-white">{activeAlerts}</p><p className="mt-2 text-xs text-amber-200">Requieren seguimiento</p></div><AlertTriangle className="h-6 w-6 text-amber-200" /></div></CardContent></Card><Card className="glass-panel"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.14em] text-slate-400">Gateway</p><p className="mt-3 text-xl font-mono font-semibold text-white">{data.gateway.status}</p><p className="mt-2 text-xs text-cyan-200">{data.gateway.name}</p></div><Radio className="h-6 w-6 text-cyan-200" /></div></CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card className="glass-panel"><CardHeader className="border-b border-white/10"><CardTitle className="flex items-center gap-2 text-slate-50"><Building2 className="h-4 w-4 text-violet-200" />Activos supervisados</CardTitle><CardDescription className="text-slate-400">Resumen de activos enlazados a tu espacio de cliente.</CardDescription></CardHeader><CardContent className="p-0">{data.machines.map(machine => <div className="flex items-center justify-between gap-3 border-b border-white/10 p-5 last:border-0" key={machine.id}><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-white/[.04]"><Gauge className="h-4 w-4 text-cyan-100" /></div><div><p className="font-medium text-white">{machine.name}</p><p className="mt-1 font-mono text-[10px] text-slate-500">{machine.machineKey} · {machine.area}</p></div></div><div className="text-right"><Badge variant="outline" className="border-white/15 text-slate-200">{machine.state}</Badge><p className="mt-2 text-[11px] text-slate-500">{machine.cycleCount} ciclos · {machine.runtimeSeconds}s</p></div></div>)}</CardContent></Card>
      <Card className="glass-panel"><CardHeader className="border-b border-white/10"><CardTitle className="flex items-center gap-2 text-slate-50"><Eye className="h-4 w-4 text-violet-200" />Límite de acceso</CardTitle></CardHeader><CardContent className="space-y-4 p-5"><div className="rounded-2xl border border-cyan-200/15 bg-cyan-200/[.06] p-4"><p className="text-sm font-medium text-cyan-50">Vista de estado y trazabilidad</p><p className="mt-2 text-xs leading-5 text-slate-300">Este portal no emite comandos. La ejecución se limita al centro de control, a confirmaciones y al gateway autorizado.</p></div><div className="space-y-3">{([{ title: "Datos", description: "Eventos, telemetría y disponibilidad", Icon: Cloud }, { title: "Seguridad", description: "Aislamiento por sesión y registro persistente", Icon: ShieldCheck }, { title: "Cobertura", description: "Simulación determinista de los activos", Icon: Sparkles }] as { title: string; description: string; Icon: LucideIcon }[]).map(({ title, description, Icon }) => <div className="flex items-start gap-3" key={title}><Icon className="mt-0.5 h-4 w-4 text-slate-400" /><div><p className="text-sm text-white">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div></div>)}</div></CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-2"><Card className="glass-panel"><CardHeader className="border-b border-white/10"><CardTitle className="text-base text-slate-50">Alertas recientes</CardTitle></CardHeader><CardContent className="p-0">{data.alerts.length ? data.alerts.slice(0, 5).map(alert => <div className="flex items-center justify-between gap-3 border-b border-white/10 p-4 last:border-0" key={alert.id}><div><p className="text-sm text-white">{alert.title}</p><p className="mt-1 text-xs text-slate-500">{alert.description}</p></div><div className="text-right"><Badge className={alert.severity === "critical" ? "bg-rose-300/15 text-rose-100" : "bg-amber-300/15 text-amber-100"}>{alert.status}</Badge><p className="mt-2 text-[10px] text-slate-500">{time(alert.createdAt)}</p></div></div>) : <p className="p-8 text-center text-sm text-slate-500">No hay alertas activas en este momento.</p>}</CardContent></Card><Card className="glass-panel"><CardHeader className="border-b border-white/10"><CardTitle className="text-base text-slate-50">Actividad verificada</CardTitle></CardHeader><CardContent className="p-0">{data.events.slice(0, 5).map(event => <div className="flex items-center justify-between gap-3 border-b border-white/10 p-4 last:border-0" key={event.id}><div><p className="font-mono text-xs text-violet-100">{event.eventType}</p><p className="mt-1 text-xs text-slate-500">Evidencia persistida en el ledger operativo</p></div><ArrowUpRight className="h-4 w-4 text-slate-500" /></div>)}</CardContent></Card></section>
  </div></div>;
}
