import React, { useEffect, useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Activity, AlertTriangle, Cable, CheckCircle2, CircleDot, CloudCog, Command, Cpu, FileText, Gauge, HeartPulse, Loader2, Play, Power, Radio, RefreshCw, RotateCcw, ShieldCheck, Siren, TimerReset, Unplug, Waves, Wrench } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const commandButtons = [
  { type: "start", label: "Start", icon: Play, critical: true },
  { type: "stop", label: "Stop", icon: Power, critical: false },
  { type: "pause", label: "Pause", icon: TimerReset, critical: false },
  { type: "resume", label: "Resume", icon: Play, critical: true },
  { type: "reset", label: "Reset", icon: RotateCcw, critical: true },
  { type: "maintenance", label: "Maintenance", icon: Wrench, critical: true },
  { type: "acknowledge_alarm", label: "Acknowledge", icon: CheckCircle2, critical: false },
  { type: "emergency_stop_simulation", label: "Emergency stop", icon: Siren, critical: true },
] as const;

function nowKey() { return typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `cmd-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function formatTime(value: string | Date | null | undefined) { return value ? new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "—"; }

export default function OperationsCenter() {
  const utils = trpc.useUtils();
  const overview = trpc.operations.overview.useQuery(undefined, { refetchInterval: 15_000 });
  const [activeMachineId, setActiveMachineId] = useState<number | null>(null);
  const [credential, setCredential] = useState<{ gatewayKey: string; token: string } | null>(null);
  const invalidate = () => utils.operations.overview.invalidate();
  const runCycle = trpc.operations.gateway.runCycle.useMutation({ onSuccess: invalidate });
  const provision = trpc.operations.gateway.provisionCredentials.useMutation({ onSuccess: value => { setCredential({ gatewayKey: value.gatewayKey, token: value.token }); invalidate(); } });
  const generateReport = trpc.operations.reports.generate.useMutation({ onSuccess: invalidate });
  const requestCommand = trpc.operations.commands.request.useMutation({ onSuccess: invalidate });
  const condition = trpc.operations.machine.simulateCondition.useMutation({ onSuccess: invalidate });

  useEffect(() => { if (overview.data?.machines[0] && activeMachineId === null) setActiveMachineId(overview.data.machines[0].id); }, [overview.data, activeMachineId]);
  useEffect(() => {
    const stream = new EventSource("/api/stream/operational");
    const refresh = () => invalidate();
    stream.addEventListener("operational", refresh);
    return () => { stream.removeEventListener("operational", refresh); stream.close(); };
  }, []);

  const data = overview.data;
  const activeMachine = data?.machines.find(machine => machine.id === activeMachineId) ?? data?.machines[0];
  const telemetry = useMemo(() => (data?.telemetry ?? []).filter(sample => sample.machineId === activeMachine?.id).map(sample => ({ time: formatTime(sample.createdAt), temperature: sample.temperature / 10, load: sample.load, energy: sample.energy, speed: sample.speed })), [data?.telemetry, activeMachine?.id]);
  if (overview.isLoading) return <div className="grid min-h-[70vh] place-items-center text-slate-400"><Loader2 className="mr-2 inline h-5 w-5 animate-spin" />Cargando el centro operativo…</div>;
  if (overview.isError || !data) return <div className="grid min-h-[70vh] place-items-center"><Card className="glass-panel max-w-md"><CardContent className="p-8 text-center"><AlertTriangle className="mx-auto h-7 w-7 text-rose-300" /><p className="mt-3 font-semibold text-white">No se pudo recuperar el estado operacional</p><Button className="mt-5" onClick={() => overview.refetch()}>Reintentar</Button></CardContent></Card></div>;

  const systemChecks = [
    { label: "Backend", value: "ONLINE", icon: CloudCog, tone: "text-emerald-200" },
    { label: "Database", value: data.health.some(check => check.component === "database" && check.status === "unhealthy") ? "DEGRADED" : "HEALTHY", icon: CircleDot, tone: "text-cyan-200" },
    { label: "Gateway", value: data.gateway.status.toUpperCase(), icon: Radio, tone: data.gateway.status === "online" ? "text-emerald-200" : "text-amber-200" },
    { label: "Machine", value: activeMachine?.connectionStatus?.toUpperCase() ?? "—", icon: Cpu, tone: activeMachine?.connectionStatus === "connected" ? "text-emerald-200" : "text-amber-200" },
  ];

  return <div className="operations-shell min-h-screen -m-4 p-4 md:-m-6 md:p-6"><div className="mx-auto max-w-[1680px] space-y-5">
    <header className="glass-panel relative overflow-hidden rounded-3xl p-5 md:p-7"><div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-cyan-300/10 blur-3xl" /><div className="relative flex flex-col justify-between gap-5 xl:flex-row xl:items-center"><div className="flex items-start gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl border border-cyan-200/30 bg-cyan-200/10 text-cyan-100 shadow-[inset_0_1px_1px_rgba(255,255,255,.22),0_8px_30px_rgba(6,182,212,.12)]"><Waves className="h-7 w-7" /></div><div><div className="flex flex-wrap items-center gap-3"><h1 className="font-mono text-xl font-semibold tracking-[.12em] text-white">UAOL—MR / OPERATIONS</h1><Badge className="border-cyan-200/30 bg-cyan-200/10 font-mono text-[10px] tracking-[.18em] text-cyan-50">SIMULATION MODE</Badge></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Centro operativo conectado a backend, cola de comandos, gateway autenticado, gemelo digital y auditoría persistente.</p></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => runCycle.mutate()} disabled={runCycle.isPending} className="glass-button"><RefreshCw className={`mr-2 h-4 w-4 ${runCycle.isPending ? "animate-spin" : ""}`} />Ejecutar ciclo</Button><Button variant="outline" onClick={() => generateReport.mutate()} disabled={generateReport.isPending} className="glass-button"><FileText className="mr-2 h-4 w-4" />Generar informe</Button><Button onClick={() => provision.mutate()} disabled={provision.isPending} className="bg-cyan-200 text-slate-950 hover:bg-cyan-100"><Cable className="mr-2 h-4 w-4" />Emitir credencial gateway</Button></div></div></header>

    {credential && <Card className="border-amber-300/30 bg-amber-300/10 text-amber-50"><CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em]">Credencial emitida una sola vez</p><p className="mt-1 text-xs text-amber-100/80">Guárdala en <code>gateway-local/.env</code>. El backend conserva solo su hash.</p><code className="mt-2 block max-w-xl overflow-auto rounded bg-slate-950/60 p-2 text-[11px]">GATEWAY_ID={credential.gatewayKey}\nGATEWAY_TOKEN={credential.token}</code></div><Button variant="outline" className="border-amber-200/40 text-amber-50" onClick={() => navigator.clipboard?.writeText(`GATEWAY_ID=${credential.gatewayKey}\nGATEWAY_TOKEN=${credential.token}`)}>Copiar</Button></CardContent></Card>}

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{systemChecks.map(check => <Card key={check.label} className="glass-panel"><CardContent className="flex items-center justify-between p-4"><div><p className="text-[10px] font-medium uppercase tracking-[.16em] text-slate-400">{check.label}</p><p className={`mt-1 font-mono text-sm font-semibold ${check.tone}`}>{check.value}</p></div><check.icon className={`h-5 w-5 ${check.tone}`} /></CardContent></Card>)}</section>

    <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Card className="glass-panel"><CardHeader className="border-b border-white/10"><div className="flex items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-slate-50"><Activity className="h-4 w-4 text-cyan-200" />Gemelo digital / Máquina</CardTitle><CardDescription className="text-slate-400">Cada lectura, estado y condición proviene del simulador persistente.</CardDescription></div><Badge variant="outline" className="border-white/15 text-slate-300">{data.hardwareMode}</Badge></div></CardHeader><CardContent className="p-4"><div className="grid gap-3 md:grid-cols-3">{data.machines.map(machine => <button key={machine.id} onClick={() => setActiveMachineId(machine.id)} className={`rounded-2xl border p-4 text-left transition ${activeMachine?.id === machine.id ? "border-cyan-200/50 bg-cyan-200/10 shadow-[0_12px_32px_rgba(6,182,212,.08)]" : "border-white/10 bg-slate-950/25 hover:border-white/25"}`}><div className="flex justify-between gap-2"><div><p className="font-medium text-slate-100">{machine.name}</p><p className="mt-1 font-mono text-[10px] text-slate-500">{machine.machineKey}</p></div><span className={`mt-1 h-2.5 w-2.5 rounded-full ${machine.connectionStatus === "connected" ? "bg-emerald-300" : "bg-rose-300"}`} /></div><p className="mt-5 font-mono text-xs uppercase text-cyan-100">{machine.state}</p><p className="mt-2 text-[11px] text-slate-400">{machine.cycleCount} ciclos · {machine.runtimeSeconds}s uptime</p></button>)}</div>
      {activeMachine && <div className="mt-4 rounded-2xl border border-white/10 bg-slate-950/25 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-semibold text-white">{activeMachine.name}</p><p className="mt-1 text-xs text-slate-400">Estado <span className="font-mono text-cyan-100">{activeMachine.state}</span> · Latencia simulada {activeMachine.simulatedLatencyMs} ms · Gateway {data.gateway.status}</p></div><div className="flex flex-wrap gap-2">{commandButtons.map(item => <Button key={item.type} size="sm" variant={item.type === "emergency_stop_simulation" ? "destructive" : "outline"} className={item.type === "emergency_stop_simulation" ? "bg-rose-500/90" : "glass-button"} onClick={() => { if (item.critical && !window.confirm(`¿Confirmar ${item.label} exclusivamente en el modo simulación?`)) return; requestCommand.mutate({ machineId: activeMachine.id, commandType: item.type, confirmed: item.critical, idempotencyKey: nowKey() }); }} disabled={requestCommand.isPending}><item.icon className="mr-1.5 h-3.5 w-3.5" />{item.label}</Button>)}</div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Carga", `${activeMachine.currentLoad}%`], ["Velocidad", `${activeMachine.currentSpeed}`], ["Ciclos", activeMachine.cycleCount], ["Conexión", activeMachine.connectionStatus]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-white/8 bg-white/[.03] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 font-mono text-sm text-slate-100">{value}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-2 border-t border-white/10 pt-4"><Button size="sm" className="glass-button" variant="outline" onClick={() => condition.mutate({ machineId: activeMachine.id, condition: "disconnect" })}><Unplug className="mr-1.5 h-3.5 w-3.5" />Desconectar</Button><Button size="sm" className="glass-button" variant="outline" onClick={() => condition.mutate({ machineId: activeMachine.id, condition: "reconnect" })}><Cable className="mr-1.5 h-3.5 w-3.5" />Reconectar</Button><Button size="sm" className="glass-button" variant="outline" onClick={() => { if (window.confirm("¿Inducir un fallo solo en el gemelo digital?")) condition.mutate({ machineId: activeMachine.id, condition: "fault", confirmed: true }); }}><AlertTriangle className="mr-1.5 h-3.5 w-3.5" />Inducir fallo</Button><Button size="sm" className="glass-button" variant="outline" onClick={() => condition.mutate({ machineId: activeMachine.id, condition: "recover" })}><Wrench className="mr-1.5 h-3.5 w-3.5" />Recuperar</Button></div></div>}</CardContent></Card>
      <Card className="glass-panel"><CardHeader className="border-b border-white/10"><CardTitle className="flex items-center gap-2 text-slate-50"><Gauge className="h-4 w-4 text-cyan-200" />Telemetría viva</CardTitle><CardDescription className="text-slate-400">Actualización automática vía SSE, con persistencia de muestras.</CardDescription></CardHeader><CardContent className="p-4"><div className="h-[280px]">{telemetry.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={telemetry}><defs><linearGradient id="tempFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#67e8f9" stopOpacity={.45} /><stop offset="100%" stopColor="#67e8f9" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="time" tick={{ fill: "#94a3b8", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#94a3b8", fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: "#0b1220e8", border: "1px solid #ffffff22", borderRadius: 12 }} /><Area type="monotone" dataKey="temperature" name="Temp. °C" stroke="#67e8f9" fill="url(#tempFill)" strokeWidth={2} /><Area type="monotone" dataKey="load" name="Carga %" stroke="#a78bfa" fill="transparent" strokeWidth={2} /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center rounded-xl border border-dashed border-white/15 text-center text-xs text-slate-500"><span><HeartPulse className="mx-auto mb-2 h-5 w-5" />Ejecuta un ciclo o inicia gateway-local.</span></div>}</div></CardContent></Card></section>

    <section className="grid gap-5 xl:grid-cols-2"><Card className="glass-panel"><CardHeader className="border-b border-white/10"><CardTitle className="flex items-center gap-2 text-slate-50"><Command className="h-4 w-4 text-cyan-200" />Cola de operaciones</CardTitle></CardHeader><CardContent className="max-h-[390px] overflow-auto p-0">{data.commands.length ? data.commands.map(command => <div key={command.id} className="border-b border-white/10 p-4 last:border-0"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-cyan-100">{command.commandId}</p><p className="mt-1 text-sm text-slate-100">{command.commandType}</p><p className="mt-1 text-[11px] text-slate-500">{formatTime(command.requestedAt)} · {command.correlationId}</p></div><Badge className={command.status === "succeeded" ? "bg-emerald-300/15 text-emerald-100" : command.status === "failed" ? "bg-rose-300/15 text-rose-100" : "bg-amber-300/15 text-amber-100"}>{command.status}</Badge></div></div>) : <p className="p-8 text-center text-sm text-slate-500">No hay comandos todavía.</p>}</CardContent></Card>
      <Card className="glass-panel"><CardHeader className="border-b border-white/10"><CardTitle className="flex items-center gap-2 text-slate-50"><ShieldCheck className="h-4 w-4 text-cyan-200" />Eventos y auditoría</CardTitle></CardHeader><CardContent className="max-h-[390px] overflow-auto p-0">{data.events.length ? data.events.map(event => <div key={event.id} className="border-b border-white/10 p-4 last:border-0"><div className="flex items-center justify-between gap-3"><p className="font-mono text-[11px] text-cyan-100">{event.eventType}</p><span className="text-[10px] text-slate-500">{formatTime(event.createdAt)}</span></div><p className="mt-2 text-xs text-slate-300">{JSON.stringify(event.payloadJson)}</p></div>) : <p className="p-8 text-center text-sm text-slate-500">No hay eventos persistidos.</p>}</CardContent></Card></section>
  </div></div>;
}
