import asyncio
from dataclasses import dataclass
from typing import Dict, List
import uuid
import json
from datetime import datetime

@dataclass
class Brand:
    name: str
    domain: str
    tagline: str
    color_primary: str
    color_secondary: str

@dataclass
class Platform:
    frontend_repo: str
    backend_repo: str
    database_schema: str
    api_spec: str

@dataclass
class GeneratedBusiness:
    id: str
    opportunity_id: str
    solution_id: str
    brand: Brand
    platform: Platform
    deployment_ready: bool
    created_at: str

class EnterpriseFactory:
    def __init__(self):
        self.generated_businesses = []

    async def generate_brand(self, title: str, description: str) -> Brand:
        words = title.lower().split()
        name = "".join([w.capitalize() for w in words[:2]])

        return Brand(
            name=name,
            domain=f"{name.lower()}.io",
            tagline=description[:60],
            color_primary="#3B82F6",
            color_secondary="#10B981"
        )

    async def generate_frontend(self, business_name: str) -> str:
        template = f"""
// {business_name} - Frontend (Next.js 14)
'use client'

import {{ useState }} from 'react'

export default function Dashboard() {{
  const [data, setData] = useState([])

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white shadow">
        <div className="max-w-7xl mx-auto px-4 py-3">
          <h1 className="text-2xl font-bold">{business_name}</h1>
        </div>
      </nav>
      <main className="max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-3 gap-4">
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-lg font-semibold">Active Users</h2>
            <p className="text-3xl font-bold text-blue-600">0</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-lg font-semibold">Revenue</h2>
            <p className="text-3xl font-bold text-green-600">€0</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-lg font-semibold">Conversion Rate</h2>
            <p className="text-3xl font-bold">0%</p>
          </div>
        </div>
      </main>
    </div>
  )
}}
"""
        return template

    async def generate_backend(self, business_name: str) -> str:
        template = f"""
# {business_name} - Backend (FastAPI)

from fastapi import FastAPI, Depends
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

app = FastAPI(title="{business_name}", version="1.0.0")

# Database
DATABASE_URL = "postgresql://user:password@localhost/db"
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)

@app.get("/health")
async def health():
    return {{"status": "ok"}}

@app.get("/api/users")
async def get_users():
    return []

@app.get("/api/revenue")
async def get_revenue():
    return {{"total": 0, "currency": "EUR"}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
"""
        return template

    async def generate_documentation(self, business_name: str) -> str:
        template = f"""
# {business_name} - Technical Documentation

## Overview
{business_name} is an autonomous business generated by AUREA X on {datetime.now().isoformat()}.

## Quick Start

1. Clone repository
2. Install dependencies
3. Configure environment variables
4. Run `docker compose up`
5. Access at http://localhost:3000

## API Endpoints

### GET /health
Health check endpoint.

### GET /api/users
Retrieve active users.

### GET /api/revenue
Retrieve revenue metrics.

## Deployment

Deploy to production:
- Frontend: Vercel
- Backend: Railway
- Database: Supabase

## Support
For issues, contact: support@{business_name.lower()}.io
"""
        return template

    async def generate_complete_business(self, opportunity_id: str, solution_id: str) -> GeneratedBusiness:
        # Brand
        brand = await self.generate_brand(
            title="Compliance Automation",
            description="Automate EU AI Act compliance for businesses"
        )

        # Code artifacts
        frontend_code = await self.generate_frontend(brand.name)
        backend_code = await self.generate_backend(brand.name)
        docs = await self.generate_documentation(brand.name)

        # Platform
        platform = Platform(
            frontend_repo=f"github.com/aurea-x/{brand.name.lower()}-frontend",
            backend_repo=f"github.com/aurea-x/{brand.name.lower()}-backend",
            database_schema="users, audits, compliance_records, logs",
            api_spec="OpenAPI 3.0.1 compliant"
        )

        business = GeneratedBusiness(
            id=str(uuid.uuid4()),
            opportunity_id=opportunity_id,
            solution_id=solution_id,
            brand=brand,
            platform=platform,
            deployment_ready=True,
            created_at=datetime.now().isoformat()
        )

        self.generated_businesses.append(business)

        return business

if __name__ == "__main__":
    async def main():
        factory = EnterpriseFactory()

        business = await factory.generate_complete_business(
            opportunity_id="opp_001",
            solution_id="sol_001"
        )

        print(f"Generated Business: {business.brand.name}")
        print(f"Domain: {business.brand.domain}")
        print(f"Backend Repo: {business.platform.backend_repo}")
        print(f"Frontend Repo: {business.platform.frontend_repo}")
        print(f"Deployment Ready: {business.deployment_ready}")

    asyncio.run(main())
